export const leadList = {
    "0": {
      "id": 0,
      "first_name": "Roman",
      "last_name":"Abramovich",
      "last_login": "11.08.2016",
      "clients_time": "19.43",
      "next_ivent": "27.15.16 12.30 Call Client Alexei",
      "clients_info": {
        "email":"belkov@gmail.com",
        "mobile_numb": "+79154455555",
        "phone_numb": "645175",
        "account_type": "Personal",
        "platform":"MT4",
        "country":"Russia",
        "town":"Smolensk",
        "state":"Smolensk",
        "post_code":"784576",
        "adress":"Adress",
        "adress2":"Adress 2",
        "birth_date":"18.02.1963",
        "Language":"Russian"
      }
    },
    "1" :{
      "id": 1,
      "first_name": "Gleb",
      "last_name":"Bondarchuk",
      "last_login": "12.08.2016",
      "clients_time": "20.43",
      "next_ivent": "27.15.16 12.30 Call Client Alexei",
      "clients_info": {
        "email":"belkov@gmail.com",
        "mobile_numb": "+79154455555",
        "phone_numb": "645175",
        "account_type": "Personal",
        "platform":"MT4",
        "country":"Russia",
        "town":"Smolensk",
        "state":"Smolensk",
        "post_code":"784576",
        "adress":"Adress",
        "adress2":"Adress 2",
        "birth_date":"18.02.1963",
        "Language":"Russian"
      }
    },
    "2" :{
      "id": 2,
      "first_name": "Pavel",
      "last_name":"Romanov",
      "last_login": "13.08.2016",
      "clients_time": "21.43",
      "next_ivent": "27.15.16 12.30 Call Client Alexei",
      "clients_info": {
        "email":"belkov@gmail.com",
        "mobile_numb": "+79154455555",
        "phone_numb": "645175",
        "account_type": "Personal",
        "platform":"MT4",
        "country":"Russia",
        "town":"Smolensk",
        "state":"Smolensk",
        "post_code":"784576",
        "adress":"Adress",
        "adress2":"Adress 2",
        "birth_date":"18.02.1963",
        "Language":"Russian"
      }
    },
    "3" :{
      "id": 3,
      "first_name": "Elvis",
      "last_name":"Rasputin",
      "last_login": "14.08.2016",
      "clients_time": "22.43",
      "next_ivent": "27.15.16 12.30 Call Client Alexei",
      "clients_info": {
        "email":"belkov@gmail.com",
        "mobile_numb": "+79154455555",
        "phone_numb": "645175",
        "account_type": "Personal",
        "platform":"MT4",
        "country":"Russia",
        "town":"Smolensk",
        "state":"Smolensk",
        "post_code":"784576",
        "adress":"Adress",
        "adress2":"Adress 2",
        "birth_date":"18.02.1963",
        "Language":"Russian"
      }
    },
    "4" :{
      "id": 4,
      "first_name": "Elena",
      "last_name":"Pristine",
      "last_login": "15.08.2016",
      "clients_time": "23.43",
      "next_ivent": "27.15.16 12.30 Call Client Alexei",
      "clients_info": {
        "email":"belkov@gmail.com",
        "mobile_numb": "+79154455555",
        "phone_numb": "645175",
        "account_type": "Personal",
        "platform":"MT4",
        "country":"Russia",
        "town":"Smolensk",
        "state":"Smolensk",
        "post_code":"784576",
        "adress":"Adress",
        "adress2":"Adress 2",
        "birth_date":"18.02.1963",
        "Language":"Russian"
      }
    },
}